from dotenv import load_dotenv
import os

load_dotenv()
SPOTIPY_CLIENT_ID = os.environ.get("SPOTIPY_CLIENT_ID")
SPOTIPY_CLIENT_SECRET = os.environ.get("SPOTIPY_CLIENT_SECRET")
SPOTIPY_REDIRECT_URI = os.environ.get("SPOTIPY_REDIRECT_URI")
SPOTIFY_USERNAME=os.environ.get("SPOTIFY_USERNAME")
SPOTIFY_SOLAR_RADIO_PLAYLIST=os.environ.get("SPOTIFY_SOLAR_RADIO_PLAYLIST")
SPOTIFY_SITTING_IN_THE_PARK_PLAYLIST=os.environ.get(
    "SPOTIFY_SITTING_IN_THE_PARK_PLAYLIST"
)
GOOGLE_API_KEY=os.environ.get("GOOGLE_API_KEY")
GOOGLE_CSE_KEY=os.environ.get("GOOGLE_CSE_KEY")
