name:
  Solar Radio Soul Energy House Chart
spider_module:
  config.solar_radio_soul_energy_house_chart_spider
spider_class:
  SolarRadioSoulEnergyHouseChartSpider
spotify_playlist:
  spotify:user:m9wnok64hlpbzmrqpdmhmmz28:playlist:3UPbnmjETswMV57hdI4Bjm
spotify_ignored_tracks:
spotify_country:
  GB
artists_split:
  - ' & '
  - ' ft '
  - ' ft. '
  - ' feat '
  - ' feat. '
  - ' presents '
  - ' pres. '
  - ' with '
  - ' and '
  -  ', '
songs_titles_split:
  - '/'
various_titles_in_one_tokens:
  - 'various tracks'
  - 'various songs'
  - ' etc'
get_only_most_played_songs_from_albums:
  True
check_released_last_year:
  True
misspelling_correctors:
  # Add them as: module name: class name.
  # They will be executed from top to bottom, until one correction is
  # accepted by Spotify
  - correctors.lastfm_misspelling_corrector: LastFMMisspellingCorrector
  - correctors.google_misspelling_corrector: GoogleMisspellingCorrector
artists_transformations: