name: CI
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: mypy check
        uses: jpetrucciani/mypy-check@master
