name: CI
 
on: [push]

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: dependencies installation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: mypy
        run: mypy --strict --ignore-missing-imports .
